version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 18-bullseye
    volumes:
      - ..:/workspaces/meetup
    command: sleep infinity
    networks:
      - frontend

  db:
    restart: unless-stopped
    image: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  jsonbox:
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://db:27017/development
    image: harlev/jsonbox
    ports:
      - "3001:3000"
    links:
      - db
    depends_on:
      - db
    networks:
      - backend
      - frontend

volumes:
  mongo_data:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
